### PR TITLE
Course Listing page

### PR DESCRIPTION
**Pull request by KhuzaimaNawab**

### CODE REVIEW

**Comment by Artlfmj** [comment]
image
Also the views is not a fix on my end, instead it breaks stuff

**Review by Artlfmj — CHANGES_REQUESTED** [review]
Please do the following ^
                                        |

**Comment by KhuzaimaNawab** [comment]
can you send me a screenshot ?

**Comment by Artlfmj** [comment]
for what?

**Comment by KhuzaimaNawab** [comment]
To know what is breaking in ui

**Comment by Artlfmj** [comment]
Happens on login

**Comment by Artlfmj** [comment]
Could you also add author and image of the course?

**Comment by KhuzaimaNawab** [comment]
sure

**Review by Artlfmj — APPROVED** [review]

**Pull request merged**
