### PR TITLE
moved data inside dotenv

### PR DESCRIPTION
**Pull request by 1-ankush-1**
issue ref - #29
commit ref - 2040e675b823d6eb5c8be67026b9a7fecc3b475d

- [x] Added example.env.txt file
- [x] Used dotenv package to get .env values 

 - dotenv configuration
```diff
+ const dotenv = require("dotenv");
+ dotenv.config();
```
- Replaced variable names
```diff
- config.mongodb_uri
- config.mongodb_uri

+ process.env.SECRET_KEY
+ process.env.MONGODB_URL
```

### CODE REVIEW

**Comment by 1-ankush-1** [comment]
> Dumb thing to ask, but could you remove the config.json 

> Dumb thing to ask, but could you remove the config.json file

done

**Review by Artlfmj — APPROVED** [review]

**Comment by Artlfmj** [comment]
Merging, looking forward to you making more complex and complete prs :) BTW are you on the Discord already?

**Comment by 1-ankush-1** [comment]
> Merging, looking forward to you making more complex and complete prs :) BTW are you on the Discord already?

no i couldn't find the link

**Comment by Artlfmj** [comment]
> > Merging, looking forward to you making more complex and complete prs :) BTW are you on the Discord already?
> 
> no i couldn't find the link

https://discord.gg/ScHSHZ6TdN

**Pull request merged**
