### PR TITLE
Bug/added csrf protection

### PR DESCRIPTION
**Pull request by 1-ankush-1**
issue ref - #22
commit ref - c2ebe95e5bf7bb915ab121845306bf6a71bbb6ce  153044b8f1bb8fa5123112e5845be41735bc136f e4a30a859b5d23d5dc77f5101eb07d949fd7d371

## Changes
- Added the  csrfProtection inside the app.js file.
```diff
+ const csrfProtection = csrf({ cookie: true });
+ app.use(csrfProtection);
```
- Added the csrfProtection middleware  between the routes that are getting the csrf token from forms.
- updated the logout function so it will destroy the session after logout.
 
## Suggestion
- There is no home for home path .so create one so user can access that after login.
- Add a setup.md file so anyone can contribute easily.
- You can put the config.json info inside the .env file.

### CODE REVIEW

**Comment by Artlfmj** [comment]
Have you tested your changes on the forms to check they work

**Comment by 1-ankush-1** [comment]
> Have you tested your changes on the forms to check they work

yup i did . just add a Home file too so it will display the home page data after login.

**Comment by Artlfmj** [comment]
Ok, you can create a new pr for your other suggestions :)

**Comment by Artlfmj** [comment]
Could you resolve conflicts?

**Comment by 1-ankush-1** [comment]
> Ok, you can create a new pr for your other suggestions :)

you should create seprate issue for them as well.

**Comment by 1-ankush-1** [comment]
> Could you resolve conflicts?

wait give me 2 min

**Comment by Artlfmj** [comment]
You can go ahead and create the issue, I will assign you once you create it

**Comment by 1-ankush-1** [comment]
> You can go ahead and create the issue, I will assign you once you create it

- resolved the conflict

**Comment by 1-ankush-1** [comment]
> You can go ahead and create the issue, I will assign you once you create it

hey i am not clear about the requirments for the Home file. you should create the issue for Home and explain what feature you would like to add in Home.

**Comment by Artlfmj** [comment]
Will say home later today

**Comment by Artlfmj** [comment]
@1-ankush-1 checked this, you did not add csrf verification on form submit

**Pull request merged**
