### PR TITLE
Refactored app.js and created config file

### PR DESCRIPTION
**Pull request by Dharansh-Neema**
- I have refactored App.js API as of now 
- make views folder accessible from anywhere 
- added some comment to make the code more readable 
- created config folder.

### CODE REVIEW

**Review by Artlfmj — CHANGES_REQUESTED** [review]
Please remove the readme file you created, a setup file will be added by #30

**Comment by Dharansh-Neema** [comment]
let's wait for the issue #30 to get closed.

**Comment by Artlfmj** [comment]
Have you tested and ran your code?

**Comment by Artlfmj** [comment]
@Dharansh-Neema is this fully tested and ready to be deployed?

**Comment by Dharansh-Neema** [comment]
Yes Sir!!! @Artlfmj

**Pull request merged**
