### PR TITLE
certificate-folder

### PR DESCRIPTION
**Pull request by hollermay**
added 6 certificate template files with added guides and resolves the issue number #16

### CODE REVIEW

**Comment by Artlfmj** [comment]
It's good by I don't want it to close the issue as other templates are always good to get. Also your templates, can you remove the your name easily?

**Comment by hollermay** [comment]
> It's good by I don't want it to close the issue as other templates are always good to get. Also your templates, can you remove the your name easily?

Yeah I can

**Comment by hollermay** [comment]
> Is it already able to change easily or do you need to commit?

I'll have to commit lol, but if you have a pdf editor you can remove that from your end too

**Comment by Artlfmj** [comment]
Please commit

**Review by Artlfmj — CHANGES_REQUESTED** [review]
Please remove your name

**Comment by hollermay** [comment]
your mean the [name] part right?

**Comment by Artlfmj** [comment]
Yes

**Comment by hollermay** [comment]
@Artlfmj I have pushed changes into the branch please review

**Review by Artlfmj — APPROVED** [review]

**Comment by Artlfmj** [comment]
Merging, if you want to work on new stuff you are more than welcome to :)

**Comment by hollermay** [comment]
> Merging, if you want to work on new stuff you are more than welcome to :)

Yeah sure you can add hacktoberfest-accepted to close the issue or I'll keep adding 2-3 new templates here

**Comment by Artlfmj** [comment]
The whole repo has hacktoberfest topic so it should count, please check. If not I will add it

**Pull request merged**
